# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DsyAdInfo',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('acode', models.CharField(blank=True, db_column='ACode', max_length=20, null=True)),
                ('postionx', models.IntegerField(blank=True, db_column='PostionX', null=True)),
                ('postiony', models.IntegerField(blank=True, db_column='PostionY', null=True)),
                ('width', models.IntegerField(blank=True, db_column='Width', null=True)),
                ('heigth', models.IntegerField(blank=True, db_column='Heigth', null=True)),
                ('type', models.IntegerField(blank=True, db_column='Type', null=True)),
                ('filepath', models.CharField(blank=True, db_column='FilePath', max_length=32, null=True)),
                ('info', models.CharField(blank=True, db_column='Info', max_length=200, null=True)),
                ('font', models.CharField(blank=True, db_column='Font', max_length=16, null=True)),
                ('fontsize', models.FloatField(blank=True, db_column='FontSize', null=True)),
                ('septime', models.IntegerField(blank=True, db_column='SepTime', null=True)),
            ],
            options={
                'db_table': 'dsy_ad_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DsyAdvertisement',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=20, null=True)),
                ('ocode', models.CharField(blank=True, db_column='OCode', max_length=20, null=True)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=64, null=True)),
                ('info', models.CharField(blank=True, db_column='Info', max_length=2000, null=True)),
                ('backimagefile', models.CharField(blank=True, db_column='BackImageFile', max_length=32, null=True)),
                ('startdate', models.CharField(blank=True, db_column='StartDate', max_length=20, null=True)),
                ('stopdate', models.CharField(blank=True, db_column='StopDate', max_length=20, null=True)),
                ('state', models.IntegerField(blank=True, db_column='State', null=True)),
            ],
            options={
                'db_table': 'dsy_advertisement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DsyDocumentDir',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=20, null=True)),
                ('pcode', models.CharField(blank=True, db_column='PCode', max_length=20, null=True)),
                ('ocode', models.CharField(blank=True, db_column='OCode', max_length=20, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=64, null=True)),
                ('info', models.CharField(blank=True, db_column='Info', max_length=200, null=True)),
            ],
            options={
                'db_table': 'dsy_document_dir',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DsyDocuments',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('dcode', models.CharField(blank=True, db_column='DCode', max_length=20, null=True)),
                ('filename', models.CharField(blank=True, db_column='FileName', max_length=64, null=True)),
                ('ext', models.CharField(blank=True, db_column='Ext', max_length=200, null=True)),
                ('uuid', models.CharField(blank=True, db_column='UUID', max_length=32, null=True)),
                ('downloadcount', models.IntegerField(blank=True, db_column='DownLoadCount', null=True)),
            ],
            options={
                'db_table': 'dsy_documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DsyEmplyees',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=20, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=32, null=True)),
                ('alias', models.CharField(blank=True, db_column='Alias', max_length=64, null=True)),
                ('ocode', models.CharField(blank=True, db_column='OCode', max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, db_column='Mobile', max_length=11, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=20, null=True)),
                ('info', models.CharField(blank=True, db_column='Info', max_length=2000, null=True)),
            ],
            options={
                'db_table': 'dsy_emplyees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DsyEmplyeesRole',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('ecode', models.CharField(blank=True, db_column='ECode', max_length=20, null=True)),
                ('rcode', models.CharField(blank=True, db_column='RCode', max_length=20, null=True)),
            ],
            options={
                'db_table': 'dsy_emplyees_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DsyFunction',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=20, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=32, null=True)),
                ('info', models.CharField(blank=True, db_column='Info', max_length=200, null=True)),
            ],
            options={
                'db_table': 'dsy_function',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DsyKnowlege',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=20, null=True)),
                ('ktcode', models.CharField(blank=True, db_column='KTCode', max_length=20, null=True)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=64, null=True)),
                ('info', models.CharField(blank=True, db_column='Info', max_length=200, null=True)),
                ('ecode', models.CharField(blank=True, db_column='ECode', max_length=20, null=True)),
                ('viewcount', models.IntegerField(blank=True, db_column='ViewCount', null=True)),
                ('fileuuids', models.CharField(blank=True, db_column='FileUUIDS', max_length=2000, null=True)),
            ],
            options={
                'db_table': 'dsy_knowlege',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DsyKnowReplay',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('kcode', models.CharField(blank=True, db_column='KCode', max_length=20, null=True)),
                ('info', models.CharField(blank=True, db_column='Info', max_length=2000, null=True)),
                ('rdate', models.CharField(blank=True, db_column='RDate', max_length=20, null=True)),
                ('ecode', models.CharField(blank=True, db_column='ECode', max_length=20, null=True)),
            ],
            options={
                'db_table': 'dsy_know_replay',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DsyKnowType',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=20, null=True)),
                ('pcode', models.CharField(blank=True, db_column='PCode', max_length=20, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=32, null=True)),
                ('info', models.CharField(blank=True, db_column='Info', max_length=200, null=True)),
            ],
            options={
                'db_table': 'dsy_know_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DsyLocation',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=20, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=2000, null=True)),
                ('count1', models.CharField(blank=True, db_column='Count1', max_length=20, null=True)),
            ],
            options={
                'db_table': 'dsy_location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DsyMeetingEmp',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=20, null=True)),
                ('mcode', models.CharField(blank=True, db_column='MCode', max_length=20, null=True)),
                ('ecode', models.CharField(blank=True, db_column='ECode', max_length=20, null=True)),
                ('jointime', models.CharField(blank=True, db_column='JoinTime', max_length=20, null=True)),
                ('exittime', models.CharField(blank=True, db_column='ExitTime', max_length=20, null=True)),
            ],
            options={
                'db_table': 'dsy_meeting_emp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DsyMeetingroom',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=20, null=True)),
                ('ocode', models.CharField(blank=True, db_column='OCode', max_length=20, null=True)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=64, null=True)),
                ('info', models.CharField(blank=True, db_column='Info', max_length=200, null=True)),
                ('starttime', models.CharField(blank=True, db_column='StartTime', max_length=20, null=True)),
                ('stoptime', models.CharField(blank=True, db_column='StopTime', max_length=20, null=True)),
                ('state', models.IntegerField(blank=True, db_column='State', null=True)),
                ('usercode', models.CharField(blank=True, db_column='UserCode', max_length=20, null=True)),
            ],
            options={
                'db_table': 'dsy_meetingroom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DsyOrganization',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=20, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=200, null=True)),
                ('account', models.CharField(blank=True, db_column='Account', max_length=20, null=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=20, null=True)),
                ('registertime', models.CharField(blank=True, db_column='RegisterTime', max_length=19, null=True)),
                ('email', models.CharField(blank=True, db_column='EMail', max_length=36, null=True)),
                ('qq', models.CharField(blank=True, db_column='QQ', max_length=20, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=20, null=True)),
                ('mobil', models.CharField(blank=True, db_column='Mobil', max_length=11, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=200, null=True)),
            ],
            options={
                'db_table': 'dsy_organization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DsyPrdEmp',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=20, null=True)),
                ('pcode', models.CharField(blank=True, db_column='PCode', max_length=20, null=True)),
                ('ecode', models.CharField(blank=True, db_column='ECode', max_length=20, null=True)),
            ],
            options={
                'db_table': 'dsy_prd_emp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DsyProductDoc',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('pcode', models.CharField(blank=True, db_column='PCode', max_length=20, null=True)),
                ('filename', models.CharField(blank=True, db_column='FileName', max_length=64, null=True)),
                ('ext', models.CharField(blank=True, db_column='Ext', max_length=200, null=True)),
                ('uuid', models.CharField(blank=True, db_column='UUID', max_length=32, null=True)),
            ],
            options={
                'db_table': 'dsy_product_doc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DsyProducts',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=20, null=True)),
                ('ocode', models.CharField(blank=True, db_column='OCode', max_length=20, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=32, null=True)),
                ('info', models.CharField(blank=True, db_column='Info', max_length=2000, null=True)),
                ('globalflag', models.IntegerField(blank=True, db_column='GlobalFlag', null=True)),
                ('state', models.IntegerField(blank=True, db_column='State', null=True)),
                ('usercode', models.CharField(blank=True, db_column='UserCode', max_length=20, null=True)),
            ],
            options={
                'db_table': 'dsy_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DsyRole',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=20, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=32, null=True)),
                ('info', models.CharField(blank=True, db_column='Info', max_length=200, null=True)),
            ],
            options={
                'db_table': 'dsy_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DsyRoleFuncs',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('rcode', models.CharField(blank=True, db_column='RCode', max_length=20, null=True)),
                ('fcode', models.CharField(blank=True, db_column='FCode', max_length=20, null=True)),
            ],
            options={
                'db_table': 'dsy_role_funcs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DsyRunlogs',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=20, null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=32, null=True)),
                ('operatortime', models.CharField(blank=True, db_column='OperatorTime', max_length=19, null=True)),
                ('account', models.CharField(blank=True, db_column='Account', max_length=20, null=True)),
                ('info', models.CharField(blank=True, db_column='Info', max_length=2000, null=True)),
                ('ocode', models.CharField(blank=True, db_column='OCode', max_length=20, null=True)),
            ],
            options={
                'db_table': 'dsy_runlogs',
                'managed': False,
            },
        ),
    ]
